-- PostgreSQL schema for ESG FOODPOINT
-- Drop tables in correct order to avoid FK constraint issues
drop table if exists public.order_items cascade;
drop table if exists public.requests cascade;
drop table if exists public.orders cascade;
drop table if exists public.menu_items cascade;
drop table if exists public.categories cascade;
drop table if exists public.users cascade;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  parent_id bigint references public.categories(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null check (role in ('admin', 'manager', 'service_desk', 'waiter', 'kitchen')),
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10, 2) not null check (price >= 0),
  category_id bigint not null references public.categories(id) on delete restrict,
  available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_type text not null check (order_type in ('dine_in', 'delivery')),
  customer_source text default 'walk_in' check (customer_source in ('walk_in', 'phone_order', 'online', 'delivery_app', 'other')),
  customer_name text,
  phone text,
  address text,
  table_number text,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'cooking', 'ready', 'on_the_way', 'served', 'delivered')),
  payment_method text check (payment_method in ('cash', 'mobile_money', 'card')),
  payment_status text default 'pending' check (payment_status in ('pending', 'paid', 'failed')),
  estimated_time_minutes integer default 30 check (estimated_time_minutes > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  instructions text,
  created_at timestamptz not null default now()
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  type text not null check (type in ('call_waiter', 'request_bill')),
  status text not null default 'pending' check (status in ('pending', 'fulfilled')),
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz not null default now(),
  unique(order_id)
);

create index if not exists idx_categories_parent_id on public.categories(parent_id);
create index if not exists idx_menu_items_category_id on public.menu_items(category_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_phone on public.orders(phone);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_requests_order_id on public.requests(order_id);
create index if not exists idx_requests_status on public.requests(status);
create index if not exists idx_feedback_order_id on public.feedback(order_id);

alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.requests enable row level security;
alter table public.users enable row level security;
alter table public.feedback enable row level security;

/* Helper functions for role checks */
create or replace function public.get_user_role(uid uuid)
  returns text language sql stable as $$
    select role from public.users where id = uid limit 1;
$$;

create or replace function public.is_admin(uid uuid)
  returns boolean language sql stable as $$
    select public.get_user_role(uid) = 'admin';
$$;

create or replace function public.is_staff(uid uuid)
  returns boolean language sql stable as $$
    select public.get_user_role(uid) IN ('admin','service_desk','kitchen','waiter','manager');
$$;

/* Secure RLS policies */
-- Categories: public read, staff manage
drop policy if exists "public read categories" on public.categories;
create policy "public read categories"
  on public.categories for select to anon, authenticated using (true);

drop policy if exists "staff manage categories" on public.categories;
create policy "staff manage categories"
  on public.categories for all to authenticated using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));

-- Menu items: public read, staff manage
drop policy if exists "public read menu items" on public.menu_items;
create policy "public read menu items"
  on public.menu_items for select to anon, authenticated using (true);

drop policy if exists "staff manage menu items" on public.menu_items;
create policy "staff manage menu items"
  on public.menu_items for all to authenticated using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));

-- Orders: staff can read/write, customers cannot read full table
drop policy if exists "staff select orders" on public.orders;
create policy "staff select orders"
  on public.orders for select to authenticated using (public.is_staff(auth.uid()));

drop policy if exists "staff insert orders" on public.orders;
create policy "staff insert orders"
  on public.orders for insert to authenticated with check (public.is_staff(auth.uid()));

drop policy if exists "staff update orders" on public.orders;
create policy "staff update orders"
  on public.orders for update to authenticated using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));

-- Order items: same as orders
drop policy if exists "staff select order_items" on public.order_items;
create policy "staff select order_items"
  on public.order_items for select to authenticated using (public.is_staff(auth.uid()));

drop policy if exists "staff insert order_items" on public.order_items;
create policy "staff insert order_items"
  on public.order_items for insert to authenticated with check (public.is_staff(auth.uid()));

drop policy if exists "staff update order_items" on public.order_items;
create policy "staff update order_items"
  on public.order_items for update to authenticated using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));

-- Users: staff manage own profile, admin can manage all
drop policy if exists "staff select users" on public.users;
create policy "staff select users"
  on public.users for select to authenticated using (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists "staff update users" on public.users;
create policy "staff update users"
  on public.users for update to authenticated using (auth.uid() = id or public.is_admin(auth.uid())) with check (auth.uid() = id or public.is_admin(auth.uid()));

-- RPC for order history by phone (accessible to authenticated users)
create or replace function public.get_orders_by_phone(p_phone text)
  returns setof public.orders language plpgsql security definer as $$
begin
  return query select * from public.orders where phone = p_phone;
end;$$;

grant execute on function public.get_orders_by_phone(text) to anon, authenticated;

-- Additional RLS Policies for remaining tables

-- Requests: public create, staff manage
drop policy if exists "public read requests" on public.requests;
create policy "public read requests"
  on public.requests for select to anon, authenticated using (true);

drop policy if exists "staff manage requests" on public.requests;
create policy "staff manage requests"
  on public.requests for all to authenticated using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));

-- Feedback: public create/read, staff manage
drop policy if exists "public read feedback" on public.feedback;
create policy "public read feedback"
  on public.feedback for select to anon, authenticated using (true);

drop policy if exists "public create feedback" on public.feedback;
create policy "public create feedback"
  on public.feedback for insert to anon, authenticated with check (true);

drop policy if exists "staff manage feedback" on public.feedback;
create policy "staff manage feedback"
  on public.feedback for all to authenticated using (public.is_staff(auth.uid())) with check (public.is_staff(auth.uid()));

-- Enable real-time for core tables (with exception handling for idempotency)
do $$
begin
  alter publication supabase_realtime add table public.orders;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.menu_items;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.order_items;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.requests;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.categories;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.feedback;
exception when others then null;
end $$;

-- Insert main categories
insert into public.categories (name, parent_id)
select *
from (
  values
    ('Drinks'::text, NULL::bigint),
    ('Meals'::text, NULL::bigint),
    ('Specials'::text, NULL::bigint),
    ('Snacks'::text, NULL::bigint)
) as seed(name, parent_id)
where not exists (
  select 1 from public.categories existing where existing.name = seed.name and existing.parent_id is null
);

-- Insert subcategories for Drinks
insert into public.categories (name, parent_id)
select name, (select id from public.categories where name = 'Drinks' and parent_id is null)
from (
  values
    ('Soft Drinks'::text),
    ('Juices'::text),
    ('Hot Drinks'::text),
    ('Water'::text)
) as seed(name)
where not exists (
  select 1 from public.categories existing where existing.name = seed.name and existing.parent_id is not null
);

-- Insert subcategories for Meals
insert into public.categories (name, parent_id)
select name, (select id from public.categories where name = 'Meals' and parent_id is null)
from (
  values
    ('Breakfast'::text),
    ('Lunch'::text),
    ('Dinner'::text)
) as seed(name)
where not exists (
  select 1 from public.categories existing where existing.name = seed.name and existing.parent_id is not null
);

-- Insert subcategories for Specials
insert into public.categories (name, parent_id)
select name, (select id from public.categories where name = 'Specials' and parent_id is null)
from (
  values
    ('Today''s Special'::text),
    ('Chef''s Special'::text),
    ('Seasonal Offers'::text)
) as seed(name)
where not exists (
  select 1 from public.categories existing where existing.name = seed.name and existing.parent_id is not null
);

-- Insert subcategories for Snacks
insert into public.categories (name, parent_id)
select name, (select id from public.categories where name = 'Snacks' and parent_id is null)
from (
  values
    ('Bites'::text),
    ('Fries'::text),
    ('Pastries'::text)
) as seed(name)
where not exists (
  select 1 from public.categories existing where existing.name = seed.name and existing.parent_id is not null
);

-- Insert menu items (prices in TSH - Tanzanian Shilling)
insert into public.menu_items (name, price, category_id, available)
select 
  seed.name,
  seed.price,
  (select id from public.categories where name = seed.category and parent_id is not null limit 1),
  seed.available
from (
  values
    ('Coconut Rice Bowl'::text, 15000::numeric, 'Lunch'::text, true::boolean),
    ('Nyama Choma Plate'::text, 25000::numeric, 'Lunch'::text, true::boolean),
    ('Passion Cooler'::text, 8000::numeric, 'Juices'::text, true::boolean),
    ('Ginger Tea'::text, 3000::numeric, 'Hot Drinks'::text, true::boolean),
    ('Chef Lunch Special'::text, 40000::numeric, 'Chef''s Special'::text, false::boolean)
) as seed(name, price, category, available)
where not exists (
  select 1 from public.menu_items existing where existing.name = seed.name
);

-- STEP 1: Create auth users in Supabase Console first, then use their real UUIDs below
-- Go to: Supabase > Authentication > Users > Create new user
-- 
-- Create 3 test accounts:
-- 1. Admin: email=admin@esgfood.com password=Admin@123456
-- 2. Service Desk: email=desk@esgfood.com password=Desk@123456  
-- 3. Kitchen: email=kitchen@esgfood.com password=Kitchen@123456
--
-- Then copy each user's UUID from the user details and replace below:

-- insert into public.users (id, name, role)
-- values 
--   ('REPLACE_WITH_ADMIN_UUID', 'Admin User', 'admin'),
--   ('REPLACE_WITH_DESK_UUID', 'Service Desk Staff', 'service_desk'),
--   ('REPLACE_WITH_KITCHEN_UUID', 'Kitchen Chef', 'kitchen')
-- on conflict (id) do nothing;

-- ============================================
-- SERVICE DESK SYSTEM TABLES
-- ============================================

-- Production: Track daily food prepared by chef
create table if not exists public.production (
  id bigint generated by default as identity primary key,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  cost_per_unit numeric(10, 2) not null check (cost_per_unit >= 0),
  total_value numeric(10, 2) generated always as (quantity * cost_per_unit) stored,
  created_at timestamptz not null default now()
);

-- Stock Opening: Items available at start of day
create table if not exists public.stock_opening (
  id bigint generated by default as identity primary key,
  item_name text not null,
  quantity integer not null check (quantity >= 0),
  recorded_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now(),
  unique(item_name, recorded_date)
);

-- Stock Usage: Internal usage tracking
create table if not exists public.stock_usage (
  id bigint generated by default as identity primary key,
  person_name text not null,
  item_name text not null,
  quantity integer not null check (quantity > 0),
  usage_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now()
);

-- Stock Closing: Items remaining at end of day
create table if not exists public.stock_closing (
  id bigint generated by default as identity primary key,
  item_name text not null,
  quantity integer not null check (quantity >= 0),
  recorded_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now(),
  unique(item_name, recorded_date)
);

-- Deliveries: Track delivery records
create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  location text not null,
  items text not null,
  waiter_name text,
  payment_status text default 'pending' check (payment_status in ('pending', 'paid')),
  created_at timestamptz not null default now()
);

-- Income: Track revenue
create table if not exists public.income (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('order', 'other')),
  amount numeric(10, 2) not null check (amount > 0),
  payment_method text check (payment_method in ('cash', 'mobile_money', 'card')),
  recorded_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now()
);

-- Expenses: Track costs
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  description text not null,
  amount numeric(10, 2) not null check (amount > 0),
  category text not null,
  recorded_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now()
);

-- Create indexes for performance
create index if not exists idx_production_created_at on public.production(created_at desc);
create index if not exists idx_stock_opening_date on public.stock_opening(recorded_date);
create index if not exists idx_stock_usage_date on public.stock_usage(usage_date);
create index if not exists idx_stock_closing_date on public.stock_closing(recorded_date);
create index if not exists idx_deliveries_created_at on public.deliveries(created_at desc);
create index if not exists idx_income_date on public.income(recorded_date);
create index if not exists idx_expenses_date on public.expenses(recorded_date);

-- Enable RLS on new tables
alter table public.production enable row level security;
alter table public.stock_opening enable row level security;
alter table public.stock_usage enable row level security;
alter table public.stock_closing enable row level security;
alter table public.deliveries enable row level security;
alter table public.income enable row level security;
alter table public.expenses enable row level security;

-- RLS Policies: Public read/create for MVP (no auth required)
drop policy if exists "public read production" on public.production;
create policy "public read production" on public.production for select to anon, authenticated using (true);
drop policy if exists "public create production" on public.production;
create policy "public create production" on public.production for insert to anon, authenticated with check (true);
drop policy if exists "authenticated update production" on public.production;
create policy "authenticated update production" on public.production for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete production" on public.production;
create policy "authenticated delete production" on public.production for delete to authenticated using (true);

drop policy if exists "public read stock_opening" on public.stock_opening;
create policy "public read stock_opening" on public.stock_opening for select to anon, authenticated using (true);
drop policy if exists "public create stock_opening" on public.stock_opening;
create policy "public create stock_opening" on public.stock_opening for insert to anon, authenticated with check (true);
drop policy if exists "authenticated update stock_opening" on public.stock_opening;
create policy "authenticated update stock_opening" on public.stock_opening for update to authenticated using (true) with check (true);

drop policy if exists "public read stock_usage" on public.stock_usage;
create policy "public read stock_usage" on public.stock_usage for select to anon, authenticated using (true);
drop policy if exists "public create stock_usage" on public.stock_usage;
create policy "public create stock_usage" on public.stock_usage for insert to anon, authenticated with check (true);
drop policy if exists "authenticated delete stock_usage" on public.stock_usage;
create policy "authenticated delete stock_usage" on public.stock_usage for delete to authenticated using (true);

drop policy if exists "public read stock_closing" on public.stock_closing;
create policy "public read stock_closing" on public.stock_closing for select to anon, authenticated using (true);
drop policy if exists "public create stock_closing" on public.stock_closing;
create policy "public create stock_closing" on public.stock_closing for insert to anon, authenticated with check (true);
drop policy if exists "authenticated update stock_closing" on public.stock_closing;
create policy "authenticated update stock_closing" on public.stock_closing for update to authenticated using (true) with check (true);

drop policy if exists "public read deliveries" on public.deliveries;
create policy "public read deliveries" on public.deliveries for select to anon, authenticated using (true);
drop policy if exists "public create deliveries" on public.deliveries;
create policy "public create deliveries" on public.deliveries for insert to anon, authenticated with check (true);
drop policy if exists "authenticated update deliveries" on public.deliveries;
create policy "authenticated update deliveries" on public.deliveries for update to authenticated using (true) with check (true);

drop policy if exists "public read income" on public.income;
create policy "public read income" on public.income for select to anon, authenticated using (true);
drop policy if exists "public create income" on public.income;
create policy "public create income" on public.income for insert to anon, authenticated with check (true);
drop policy if exists "authenticated update income" on public.income;
create policy "authenticated update income" on public.income for update to authenticated using (true) with check (true);

drop policy if exists "public read expenses" on public.expenses;
create policy "public read expenses" on public.expenses for select to anon, authenticated using (true);
drop policy if exists "public create expenses" on public.expenses;
create policy "public create expenses" on public.expenses for insert to anon, authenticated with check (true);
drop policy if exists "authenticated update expenses" on public.expenses;
create policy "authenticated update expenses" on public.expenses for update to authenticated using (true) with check (true);

-- ============================================
-- FINANCIAL INTELLIGENCE TABLES (NEW)
-- ============================================

-- Item Costs: Track cost of goods sold per menu item
create table if not exists public.item_costs (
  id uuid primary key default gen_random_uuid(),
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  cost_per_unit numeric(10, 2) not null check (cost_per_unit >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(menu_item_id)
);

-- Financial Expenses: Operating costs, utilities, payroll, etc.
create table if not exists public.financial_expenses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  amount numeric(10, 2) not null check (amount > 0),
  type text not null check (type in ('fixed', 'variable')),
  category text,
  description text,
  expense_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now()
);

-- Create indexes for performance
create index if not exists idx_item_costs_menu_item_id on public.item_costs(menu_item_id);
create index if not exists idx_financial_expenses_date on public.financial_expenses(expense_date desc);
create index if not exists idx_financial_expenses_type on public.financial_expenses(type);

-- Enable RLS on new financial tables
alter table public.item_costs enable row level security;
alter table public.financial_expenses enable row level security;

-- RLS Policies for item_costs
drop policy if exists "public read item_costs" on public.item_costs;
create policy "public read item_costs" on public.item_costs 
  for select to anon, authenticated using (true);

drop policy if exists "authenticated manage item_costs" on public.item_costs;
create policy "authenticated manage item_costs" on public.item_costs 
  for all to authenticated using (true) with check (true);

-- RLS Policies for financial_expenses
drop policy if exists "public read financial_expenses" on public.financial_expenses;
create policy "public read financial_expenses" on public.financial_expenses 
  for select to anon, authenticated using (true);

drop policy if exists "authenticated manage financial_expenses" on public.financial_expenses;
create policy "authenticated manage financial_expenses" on public.financial_expenses 
  for all to authenticated using (true) with check (true);

-- ============================================
-- POS EXTENSIONS: INVENTORY, PAYMENTS, ROLES
-- ============================================

-- Safely extend staff roles without renaming the users table.
alter table if exists public.users
drop constraint if exists users_role_check;

alter table if exists public.users
add constraint users_role_check
check (role in ('admin', 'service_desk', 'kitchen', 'manager', 'waiter'));

-- Safely extend order statuses for cancellation and waste tracking.
alter table if exists public.orders
drop constraint if exists orders_status_check;

alter table if exists public.orders
add constraint orders_status_check
check (status in ('pending', 'accepted', 'cooking', 'ready', 'on_the_way', 'served', 'delivered', 'cancelled', 'waste'));

-- Payment architecture. Existing payment columns are left in place; these additions are idempotent.
alter table if exists public.orders
drop constraint if exists orders_payment_method_check;

alter table if exists public.orders
add constraint orders_payment_method_check
check (payment_method in ('cash', 'mobile_money', 'mobile', 'card'));

alter table if exists public.orders
add column if not exists transaction_ref text;

-- Inventory: One stock row per menu item.
create table if not exists public.inventory (
  id uuid primary key default gen_random_uuid(),
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  stock_quantity numeric(10, 2) not null default 0 check (stock_quantity >= 0),
  unit text not null default 'pcs' check (unit in ('kg', 'pcs', 'liters')),
  low_stock_threshold numeric(10, 2) not null default 5 check (low_stock_threshold >= 0),
  prevent_order_when_empty boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(menu_item_id)
);

-- Inventory movements: Keeps an audit trail for sales adjustments and manual corrections.
create table if not exists public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  inventory_id uuid references public.inventory(id) on delete set null,
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  order_id bigint references public.orders(id) on delete set null,
  movement_type text not null check (movement_type in ('sale', 'manual_adjustment', 'restock', 'waste', 'cancel')),
  quantity_delta numeric(10, 2) not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_menu_item_id on public.inventory(menu_item_id);
create index if not exists idx_inventory_low_stock on public.inventory(stock_quantity, low_stock_threshold);
create index if not exists idx_inventory_movements_menu_item_id on public.inventory_movements(menu_item_id);
create index if not exists idx_inventory_movements_order_id on public.inventory_movements(order_id);
create index if not exists idx_inventory_movements_created_at on public.inventory_movements(created_at desc);
create index if not exists idx_orders_transaction_ref on public.orders(transaction_ref);

alter table public.inventory enable row level security;
alter table public.inventory_movements enable row level security;

drop policy if exists "public read inventory" on public.inventory;
create policy "public read inventory" on public.inventory
  for select to anon, authenticated using (true);

drop policy if exists "authenticated manage inventory" on public.inventory;
create policy "authenticated manage inventory" on public.inventory
  for all to authenticated using (true) with check (true);

drop policy if exists "public read inventory_movements" on public.inventory_movements;
create policy "public read inventory_movements" on public.inventory_movements
  for select to anon, authenticated using (true);

drop policy if exists "authenticated manage inventory_movements" on public.inventory_movements;
create policy "authenticated manage inventory_movements" on public.inventory_movements
  for all to authenticated using (true) with check (true);

-- Publish new tables for real-time (with exception handling for idempotency)
do $$
begin
  alter publication supabase_realtime add table public.item_costs;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.financial_expenses;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.inventory;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.inventory_movements;
exception when others then null;
end $$;

-- ============================================
-- PHASE A: EXTENDED RESTAURANT OPERATIONS
-- ============================================

-- Extend order types (customer_source already added in initial table creation)
alter table if exists public.orders
drop constraint if exists orders_order_type_check;

alter table if exists public.orders
add constraint orders_order_type_check
check (order_type in ('dine_in', 'delivery', 'phone_call', 'waiter_created', 'online'));

-- Extend menu availability
alter table if exists public.menu_items
add column if not exists available_morning boolean not null default true;

alter table if exists public.menu_items
add column if not exists available_afternoon boolean not null default true;

alter table if exists public.menu_items
add column if not exists available_evening boolean not null default true;

-- Extend inventory movements for production
alter table if exists public.inventory_movements
drop constraint if exists inventory_movements_movement_type_check;

alter table if exists public.inventory_movements
add constraint inventory_movements_movement_type_check
check (movement_type in ('sale', 'manual_adjustment', 'restock', 'waste', 'cancel', 'production_input', 'production_output', 'leftover_return'));

-- Production Batches
create table if not exists public.production_batches (
  id uuid primary key default gen_random_uuid(),
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  quantity_produced numeric(10, 2) not null check (quantity_produced > 0),
  remaining_quantity numeric(10, 2) not null check (remaining_quantity >= 0),
  cost_per_unit numeric(10, 2) not null default 0 check (cost_per_unit >= 0),
  total_cost numeric(10, 2) generated always as (quantity_produced * cost_per_unit) stored,
  production_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

-- Production Usage: Track batch consumption per order item (FIFO)
create table if not exists public.production_usage (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  batch_id uuid not null references public.production_batches(id) on delete restrict,
  menu_item_id bigint not null references public.menu_items(id) on delete restrict,
  quantity numeric(10, 2) not null check (quantity > 0),
  created_at timestamptz not null default now()
);

-- Suppliers: Optional supplier records for ingredient purchasing.
create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  notes text,
  created_at timestamptz not null default now()
);

-- Ingredients: Raw materials used to produce menu items.
create table if not exists public.ingredients (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  unit text not null default 'pcs' check (unit in ('g', 'kg', 'ml', 'liters', 'pcs', 'portion')),
  current_stock numeric(12, 3) not null default 0 check (current_stock >= 0),
  low_stock_threshold numeric(12, 3) not null default 0 check (low_stock_threshold >= 0),
  supplier_id uuid references public.suppliers(id) on delete set null,
  cost_per_unit numeric(12, 4) not null default 0 check (cost_per_unit >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Recipes: A normalized bill of materials for producing a menu item.
create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  menu_item_id bigint unique references public.menu_items(id) on delete set null,
  expected_yield numeric(10, 2) not null default 1 check (expected_yield > 0),
  yield_unit text not null default 'pcs',
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Recipe Items: Ingredients and quantities required for a full recipe yield.
create table if not exists public.recipe_items (
  id uuid primary key default gen_random_uuid(),
  recipe_id uuid not null references public.recipes(id) on delete cascade,
  ingredient_id uuid not null references public.ingredients(id) on delete restrict,
  quantity_required numeric(12, 3) not null check (quantity_required > 0),
  unit text not null default 'pcs' check (unit in ('g', 'kg', 'ml', 'liters', 'pcs', 'portion')),
  created_at timestamptz not null default now(),
  unique(recipe_id, ingredient_id)
);

-- Ingredient movements: Full audit trail for restocks and production consumption.
create table if not exists public.ingredient_movements (
  id uuid primary key default gen_random_uuid(),
  ingredient_id uuid not null references public.ingredients(id) on delete restrict,
  movement_type text not null check (movement_type in ('restock', 'production', 'adjustment', 'waste')),
  quantity_delta numeric(12, 3) not null,
  unit_cost numeric(12, 4),
  production_batch_id uuid references public.production_batches(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

-- Production ingredient usage: Exact ingredient cost breakdown per batch.
create table if not exists public.production_ingredient_usage (
  id uuid primary key default gen_random_uuid(),
  production_batch_id uuid not null references public.production_batches(id) on delete cascade,
  recipe_id uuid references public.recipes(id) on delete set null,
  ingredient_id uuid not null references public.ingredients(id) on delete restrict,
  quantity_used numeric(12, 3) not null check (quantity_used > 0),
  unit text not null,
  cost_per_unit numeric(12, 4) not null default 0 check (cost_per_unit >= 0),
  total_cost numeric(12, 2) generated always as (quantity_used * cost_per_unit) stored,
  created_at timestamptz not null default now()
);

alter table public.menu_items
  add column if not exists recipe_id uuid references public.recipes(id) on delete set null;

alter table public.production_batches
  add column if not exists recipe_id uuid references public.recipes(id) on delete set null;

-- Supplier Debts
create table if not exists public.debts (
  id uuid primary key default gen_random_uuid(),
  supplier_name text not null,
  item_supplied text not null,
  total_amount numeric(10, 2) not null check (total_amount > 0),
  paid_amount numeric(10, 2) not null default 0 check (paid_amount >= 0),
  remaining_balance numeric(10, 2) generated always as (total_amount - paid_amount) stored,
  status text not null default 'unpaid' check (status in ('unpaid', 'partial', 'paid')),
  transaction_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Waiter Payments
create table if not exists public.waiter_payments (
  id uuid primary key default gen_random_uuid(),
  waiter_name text not null,
  amount numeric(10, 2) not null check (amount > 0),
  payment_type text not null check (payment_type in ('wage', 'tip', 'bonus', 'commission')),
  payment_date date not null default CURRENT_DATE,
  created_at timestamptz not null default now()
);

-- Payment Transactions
create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  order_id bigint references public.orders(id) on delete set null,
  amount numeric(10, 2) not null check (amount > 0),
  method text not null check (method in ('cash', 'mobile_money', 'card', 'credit')),
  status text not null default 'completed' check (status in ('pending', 'completed', 'failed', 'refunded')),
  reference_code text,
  transaction_date timestamptz not null default now()
);

-- Create indexes
create index if not exists idx_production_batches_menu_item_id on public.production_batches(menu_item_id);
create index if not exists idx_production_batches_created_at on public.production_batches(created_at asc);
create index if not exists idx_production_usage_order_id on public.production_usage(order_id);
create index if not exists idx_production_usage_batch_id on public.production_usage(batch_id);
create index if not exists idx_ingredients_supplier_id on public.ingredients(supplier_id);
create index if not exists idx_recipes_menu_item_id on public.recipes(menu_item_id);
create index if not exists idx_recipe_items_recipe_id on public.recipe_items(recipe_id);
create index if not exists idx_recipe_items_ingredient_id on public.recipe_items(ingredient_id);
create index if not exists idx_ingredient_movements_ingredient_id on public.ingredient_movements(ingredient_id);
create index if not exists idx_ingredient_movements_created_at on public.ingredient_movements(created_at desc);
create index if not exists idx_production_ingredient_usage_batch_id on public.production_ingredient_usage(production_batch_id);
create index if not exists idx_production_ingredient_usage_ingredient_id on public.production_ingredient_usage(ingredient_id);
create index if not exists idx_debts_supplier on public.debts(supplier_name);
create index if not exists idx_payment_transactions_order on public.payment_transactions(order_id);

-- Enable RLS
alter table public.production_batches enable row level security;
alter table public.production_usage enable row level security;
alter table public.suppliers enable row level security;
alter table public.ingredients enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_items enable row level security;
alter table public.ingredient_movements enable row level security;
alter table public.production_ingredient_usage enable row level security;
alter table public.debts enable row level security;
alter table public.waiter_payments enable row level security;
alter table public.payment_transactions enable row level security;

-- Public read / Authenticated manage for MVP (to match other tables without breaking)
drop policy if exists "public read production_batches" on public.production_batches;
create policy "public read production_batches" on public.production_batches for select to anon, authenticated using (true);
drop policy if exists "authenticated manage production_batches" on public.production_batches;
create policy "authenticated manage production_batches" on public.production_batches for all to authenticated using (true) with check (true);

drop policy if exists "public read production_usage" on public.production_usage;
create policy "public read production_usage" on public.production_usage for select to anon, authenticated using (true);
drop policy if exists "authenticated manage production_usage" on public.production_usage;
create policy "authenticated manage production_usage" on public.production_usage for all to authenticated using (true) with check (true);

drop policy if exists "public read suppliers" on public.suppliers;
create policy "public read suppliers" on public.suppliers for select to anon, authenticated using (true);
drop policy if exists "authenticated manage suppliers" on public.suppliers;
create policy "authenticated manage suppliers" on public.suppliers for all to authenticated using (true) with check (true);

drop policy if exists "public read ingredients" on public.ingredients;
create policy "public read ingredients" on public.ingredients for select to anon, authenticated using (true);
drop policy if exists "authenticated manage ingredients" on public.ingredients;
create policy "authenticated manage ingredients" on public.ingredients for all to authenticated using (true) with check (true);

drop policy if exists "public read recipes" on public.recipes;
create policy "public read recipes" on public.recipes for select to anon, authenticated using (true);
drop policy if exists "authenticated manage recipes" on public.recipes;
create policy "authenticated manage recipes" on public.recipes for all to authenticated using (true) with check (true);

drop policy if exists "public read recipe_items" on public.recipe_items;
create policy "public read recipe_items" on public.recipe_items for select to anon, authenticated using (true);
drop policy if exists "authenticated manage recipe_items" on public.recipe_items;
create policy "authenticated manage recipe_items" on public.recipe_items for all to authenticated using (true) with check (true);

drop policy if exists "public read ingredient_movements" on public.ingredient_movements;
create policy "public read ingredient_movements" on public.ingredient_movements for select to anon, authenticated using (true);
drop policy if exists "authenticated manage ingredient_movements" on public.ingredient_movements;
create policy "authenticated manage ingredient_movements" on public.ingredient_movements for all to authenticated using (true) with check (true);

drop policy if exists "public read production_ingredient_usage" on public.production_ingredient_usage;
create policy "public read production_ingredient_usage" on public.production_ingredient_usage for select to anon, authenticated using (true);
drop policy if exists "authenticated manage production_ingredient_usage" on public.production_ingredient_usage;
create policy "authenticated manage production_ingredient_usage" on public.production_ingredient_usage for all to authenticated using (true) with check (true);

drop policy if exists "public read debts" on public.debts;
create policy "public read debts" on public.debts for select to anon, authenticated using (true);
drop policy if exists "authenticated manage debts" on public.debts;
create policy "authenticated manage debts" on public.debts for all to authenticated using (true) with check (true);

drop policy if exists "public read waiter_payments" on public.waiter_payments;
create policy "public read waiter_payments" on public.waiter_payments for select to anon, authenticated using (true);
drop policy if exists "authenticated manage waiter_payments" on public.waiter_payments;
create policy "authenticated manage waiter_payments" on public.waiter_payments for all to authenticated using (true) with check (true);

drop policy if exists "public read payment_transactions" on public.payment_transactions;
create policy "public read payment_transactions" on public.payment_transactions for select to anon, authenticated using (true);
drop policy if exists "authenticated manage payment_transactions" on public.payment_transactions;
create policy "authenticated manage payment_transactions" on public.payment_transactions for all to authenticated using (true) with check (true);

-- Publish new tables for real-time
do $$
begin
  alter publication supabase_realtime add table public.production_batches;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.production_usage;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.ingredients;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.recipes;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.recipe_items;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.ingredient_movements;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.production_ingredient_usage;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.debts;
exception when others then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.payment_transactions;
exception when others then null;
end $$;
